ALTER TABLE users
    ADD COLUMN IF NOT EXISTS class_code VARCHAR (255);

ALTER TABLE cpa_profiles
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE gpa_profiles
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE grade_subject_average_profiles
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();